spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/notifications
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/notifications
    user: postgres
    password: postgres
  mail:
    host: smtp.mail.ru
    port: 465
    username: gleb.laptev.00@bk.ru
#    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

kafka:
  host: "localhost:9093"

server:
  port: 8085


logging:
  level:
    org:
      springframework:
        security: DEBUG