spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${FLYWAY_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: smtp.mail.ru
    port: 465
    username: gleb.laptev.00@bk.ru
#    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

kafka:
  host: ${KAFKA_HOST}

server:
  port: 8085


logging:
  level:
    org:
      springframework:
        security: DEBUG